version: '3.1'
services:
  redis:
    image: redis
    expose:
      - 6379
  ui:
    image: us.gcr.io/anymessage-219921/ui:latest
    build: ./ui
    command: npm run dev
    volumes:
      - /usr/ui/.next
      - /usr/ui/node_modules/
      - ui-sync:/usr/ui:nocopy
    environment:
      - API_ENDPOINT=http://localhost:${API_PORT}
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file: .env
  api:
    image: us.gcr.io/anymessage-219921/api:latest
    build: ./api
    command: npm run dev
    volumes:
      - /usr/ui/dist
      - /usr/ui/node_modules/
      - api-sync:/usr/ui:nocopy
    ports:
      - "1337:1337"
      - "9223:9223"
    depends_on:
      - db
    env_file: .env
  db:
    image: postgres
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    env_file: .env
  db-migrate:
    image: us.gcr.io/anymessage-219921/db-migrate:latest
    build: ./db
    restart: on-failure
    environment:
      - TARGET_URI=db:postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DATABASE}
      - SQITCH_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-sync:/work:nocopy
    depends_on:
      - db
    env_file: .env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  database:
  ui-sync:
    external: true
  api-sync:
    external: true
  db-sync:
    external: true