version: '3.1'
services:
  redis:
    image: redis
    expose:
      - 6379
  ui:
    image: us.gcr.io/anymessage-219921/ui:latest
    build: ./ui
    command: npm run dev
    volumes:
      - /c/Users/danie/projects/anymessage/ui/customization:/usr/ui/customization
      - /c/Users/danie/projects/anymessage/ui/pages:/usr/ui/pages
      - /c/Users/danie/projects/anymessage/ui/src:/usr/ui/src
      - /c/Users/danie/projects/anymessage/ui/static:/usr/ui/static
    environment:
      - API_ENDPOINT=http://localhost:${API_PORT}
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file: .env
  api:
    image: us.gcr.io/anymessage-219921/api:latest
    build: ./api
    command: npm run dev
    volumes:
      - /c/Users/danie/projects/anymessage/api/src:/usr/api/src
    ports:
      - "1337:1337"
      - "9223:9223"
    depends_on:
      - db
    env_file: .env
  db:
    image: postgres
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    env_file: .env
  db-migrate:
    image: us.gcr.io/anymessage-219921/db-migrate:latest
    build: ./db
    restart: on-failure
    environment:
      - TARGET_URI=db:postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DATABASE}
      - SQITCH_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db:/work
    depends_on:
      - db
    env_file: .env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  database: